############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/#services"
weight = 2

[[main]]
name = "Benefits"
url = "/#benefits"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Testimonials"
url = "/#testimonials"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6


# footer menu
[[footer]]
name = "Services"
url = "/#services"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

[[footer]]
name = "Contact"
url = "/contact"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 4
